### ISSUE TITLE
Upload CSAR fail due to BPMN type casting

### ISSUE THREAD

**Issue by kuangyu0801** [kuangyu0801/master-thesis#45]
[MyTinyToDo_Bare_Docker.csar] failed with an exception
java.lang.ClassCastException: class org.opentosca.planbuilder.model.plan.bpmn.BPMNPlan cannot be cast to class org.opentosca.planbuilder.model.plan.bpel.BPELPlan (org.opentosca.planbuilder.model.plan.bpmn.BPMNPlan and org.opentosca.planbuilder.model.plan.bpel.BPELPlan are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @4f1fe01e)
	at org.opentosca.planbuilder.export.WineryExporter.exportBPELToCSAR(WineryExporter.java:227)
	at org.opentosca.planbuilder.export.WineryExporter.exportToCSAR(WineryExporter.java:94)
	at org.opentosca.container.api.service.CsarService.generatePlans(CsarService.java:62)
	at org.opentosca.container.api.controller.CsarController.handleCsarUpload(CsarController.java:304)
	at org.opentosca.container.api.controller.CsarController.uploadCsar(CsarController.java:194)

csar/MyTinyToDo_Bare_Docker.csar

**Comment by kuangyu0801** [comment]
at org.opentosca.planbuilder.export.WineryExporter.exportBPELToCSAR(WineryExporter.java:227)

Root cause:
size mismatch: exportedPlans.size() != plansToExport.size() 
BPMN Plan is added to plansToExport however, will never be add to exportedPlans

**Comment by kuangyu0801** [comment]
https://github.com/OpenTOSCA/container/commit/38caa9db5251444aa4fcc32faf26c7563e2e3c6f
