### ISSUE TITLE
DOM Exception

### ISSUE THREAD

**Issue by kuangyu0801** [kuangyu0801/master-thesis#60]
org.w3c.dom.DOMException: WRONG_DOCUMENT_ERR: A node is used in a different document than the one that created it.
at org.apache.xerces.dom.ParentNode.internalInsertBefore(Unknown Source)
	at org.apache.xerces.dom.ParentNode.insertBefore(Unknown Source)
	at org.apache.xerces.dom.NodeImpl.appendChild(Unknown Source)
	at org.opentosca.planbuilder.core.bpmn.fragments.BPMNProcessFragments.addIncomings(BPMNProcessFragments.java:283)
	at org.opentosca.planbuilder.core.bpmn.fragments.BPMNProcessFragments.createBPMNEndEventAsNode(BPMNProcessFragments.java:319)

**Comment by kuangyu0801** [comment]
Resolution: Using import node,
Follow up: #65
