### ISSUE TITLE
Show Exception Status and Setup

### ISSUE THREAD

**Issue by kuangyu0801** [kuangyu0801/master-thesis#61]
Reproduce Step: Start opentosca-docker (excluding container, container-repository, winery, and proxy) and Container: https://github.com/OpenTOSCA/container/commit/0de1c66b7539f805678aef4f59c936e9e1df79be , and upload https://github.com/kuangyu0801/master-thesis/blob/main/csar/MyTinyToDo_Bare_Docker.csar via UI

2022-01-23 15:57:25.019 WARN  [http-nio-1337-exec-1] o.o.c.connector.ode.OdeConnector         : PID is null! Not possible to find Endpoints on ODE
2022-01-23 15:57:25.019 ERROR [http-nio-1337-exec-1] o.o.c.e.p.p.bpel.BpelPlanEnginePlugin    : Error while processing plan
2022-01-23 15:57:25.019 ERROR [http-nio-1337-exec-1] o.o.c.e.p.p.bpel.BpelPlanEnginePlugin    : ProcessId is null
2022-01-23 15:57:25.019 ERROR [http-nio-1337-exec-1] o.o.c.e.p.p.bpel.BpelPlanEnginePlugin    : Endpoint for process is null
2022-01-23 15:57:25.271 INFO  [http-nio-1337-exec-1] o.o.c.e.p.p.bpel.BpelPlanEnginePlugin    : Deploying Plan: MyTinyToDo_Bare_Docker_buildPlan.zip
2022-01-23 15:57:25.424 ERROR [http-nio-1337-exec-1] o.o.c.connector.ode.OdeConnector         : RemoteException: Server not available
org.apache.axis.AxisFault: ; nested exception is: 
	java.net.ConnectException: Connection refused
	at org.apache.axis.AxisFault.makeFault(AxisFault.java:101)
	at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:154)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)

**Comment by kuangyu0801** [comment]
https://github.com/OpenTOSCA/container/commit/0ef76d2ca85c374d80c707c15910f4477e17cccf

**Comment by kuangyu0801** [comment]
ROOT Cause: Can not find ODE endpoint with inconsistent IP setting in container
FIX: be sure the check ip address setting in application.properties: org.opentosca.container.hostname=192.168.0.101

make sure it always consistent with IP in "ifconfig"

en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether c4:b3:01:bd:ab:ff 
	inet6 fe80::1c91:3139:be50:f2c1%en0 prefixlen 64 secured scopeid 0x4 
	**inet 192.168.0.101** netmask 0xffffff00 broadcast 192.168.0.255
